from pathlib import Path
from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parents[1]
ADS = ROOT / "assets" / "ads"

# Source PNG aliases generated by ChatGPT/image tools -> canonical site image names.
MAPPING = {
    "marraqueta": ["marraqueta.png", "pan-caliente.png"],
    "cafe-pasillo": ["cafepasillo.png", "cafe-pasillo.png"],
    "completo-italiano": ["completo.png", "completo-italiano.png"],
    "archivador-sentimental": ["archivador.png", "archivador-sentimental.png"],
    "timbre-mistico": ["timbre.png", "timbre-mistico.png"],
    "plantita": ["plantita.png"],
}

SIZES = {
    "960": (960, 320),
    "640": (640, 213),
}

def find_source(names):
    for name in names:
        path = ADS / name
        if path.exists():
            return path
    return None

def save_jpeg_cover(source, target, size):
    image = Image.open(source).convert("RGB")
    image = ImageOps.fit(image, size, method=Image.Resampling.LANCZOS, centering=(0.5, 0.5))
    image.save(target, "JPEG", quality=82, optimize=True, progressive=True)


def main():
    ADS.mkdir(parents=True, exist_ok=True)
    missing = []
    for canonical, names in MAPPING.items():
        source = find_source(names)
        if not source:
            missing.append(f"{canonical}: esperaba uno de {', '.join(names)}")
            continue
        for suffix, size in SIZES.items():
            target = ADS / f"{canonical}-{suffix}.jpg"
            save_jpeg_cover(source, target, size)
            print(f"OK {source.name} -> {target.name}")
    if missing:
        print("\nNo encontré estas fuentes PNG:")
        for item in missing:
            print("-", item)

if __name__ == "__main__":
    main()
