(() => {
  "use strict";
  const API = "https://receptores-analytics.adminbase100.workers.dev";
  const REASONS = ["rapidez", "comunicacion", "disponibilidad", "cumplimiento", "trato", "honorarios"];
  const LABELS = { rapidez: "Rapidez", comunicacion: "Comunicación", disponibilidad: "Disponibilidad", cumplimiento: "Cumplimiento", trato: "Trato", honorarios: "Honorarios" };
  const DEBUG = new URLSearchParams(location.search).get("debug") === "ratings";
  const cache = new Map();
  const log = (...args) => DEBUG && console.log("[ratings]", ...args);
  function browserId() {
    try { let id = localStorage.getItem("receptores_browser_id"); if (!/^[A-Za-z0-9_-]{16,128}$/.test(id || "")) { id = crypto.randomUUID().replaceAll("-", ""); localStorage.setItem("receptores_browser_id", id); } return id; } catch { return ""; }
  }
  function myVote(id) { try { return Number(localStorage.getItem(`receptores_vote:${id}`)) || 0; } catch { return 0; } }
  function setMyVote(id, vote) { try { localStorage.setItem(`receptores_vote:${id}`, String(vote)); } catch {} }
  function debugError(error) { log("error", error); }
  function widget(id) {
    const root = document.createElement("section"); root.className = "rating-widget"; root.dataset.receptorId = id; root.setAttribute("aria-label", "Calidad del servicio");
    root.innerHTML = `<div class="rating-title">Calidad del servicio</div><div class="rating-summary" aria-live="polite">Cargando evaluaciones…</div><div class="rating-actions"><button type="button" data-vote="1" aria-label="Evaluar positivamente" aria-pressed="false">Positiva</button><button type="button" data-vote="-1" aria-label="Evaluar negativamente" aria-pressed="false">Negativa</button></div><p class="rating-note">Las evaluaciones son anónimas. Los comentarios no se publican automáticamente.</p><form class="rating-details" hidden><fieldset><legend>¿Qué influyó en tu evaluación?</legend>${REASONS.map(reason => `<label><input type="checkbox" name="reason" value="${reason}"> ${LABELS[reason]}</label>`).join("")}</fieldset><label class="rating-comment">Comentario opcional<textarea name="comment" maxlength="300" rows="3"></textarea></label><div class="turnstile-slot"></div><button type="submit">Guardar detalles</button><span class="rating-message" role="status"></span></form>`;
    root.addEventListener("click", event => { const button = event.target.closest("button[data-vote]"); if (button) choose(root, Number(button.dataset.vote)); });
    root.querySelector("form").addEventListener("submit", event => { event.preventDefault(); submitDetails(root); });
    return root;
  }
  function update(root, rating) { const total = rating.total || 0; root.querySelector(".rating-summary").textContent = total < 5 ? `${total} ${total === 1 ? "evaluación" : "evaluaciones"}` : `${rating.positive_pct}% positivas · ${total} evaluaciones`; const vote = myVote(root.dataset.receptorId); root.querySelectorAll("button[data-vote]").forEach(button => { const active = Number(button.dataset.vote) === vote; button.classList.toggle("is-selected", active); button.setAttribute("aria-pressed", String(active)); }); }
  function choose(root, vote) { setMyVote(root.dataset.receptorId, vote); update(root, cache.get(root.dataset.receptorId) || { total: 0 }); root.querySelector(".rating-details").hidden = false; ensureTurnstile(root, () => submitDetails(root)); root.querySelector(".rating-message").textContent = ""; }
  function ensureTurnstile(root, onSolved) { const key = window.RECEPTORES_TURNSTILE_SITE_KEY || ""; const slot = root.querySelector(".turnstile-slot"); if (!key) { slot.textContent = "Configura Turnstile para guardar el voto."; return; } if (slot.dataset.ready) return; slot.dataset.ready = "1"; if (window.turnstile) window.turnstile.render(slot, { sitekey: key, callback: token => { slot.dataset.token = token; if (onSolved) onSolved(); }, "expired-callback": () => { delete slot.dataset.token; } }); }
  async function submitDetails(root) { const form = root.querySelector("form"), id = root.dataset.receptorId, vote = myVote(id), token = root.querySelector(".turnstile-slot").dataset.token || "", reasons = [...form.querySelectorAll("input[name=reason]:checked")].map(input => input.value), comment = form.comment.value.trim(), message = root.querySelector(".rating-message"); if (!token) { message.textContent = "Completa la verificación de seguridad para guardar."; return; } const payload = { receptor_id: id, vote, browser_id: browserId(), turnstile_token: token, reasons, comment }; log("vote sent", { ...payload, turnstile_token: "[redacted]" }); try { const response = await fetch(`${API}/vote`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); log("vote response", data); if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`); cache.set(id, data); update(root, data); message.textContent = "Detalles guardados."; } catch (error) { message.textContent = "No fue posible guardar los detalles."; debugError(error); } }
  async function load(ids) { const missing = [...new Set(ids)].filter(id => !cache.has(id)); if (!missing.length) return; log("batch requested", missing); try { const response = await fetch(`${API}/ratings?ids=${encodeURIComponent(missing.join(","))}`); const data = await response.json(); if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`); log("batch received", data); Object.entries(data.ratings || {}).forEach(([id, rating]) => cache.set(id, rating)); } catch (error) { debugError(error); } document.querySelectorAll(".rating-widget").forEach(root => { if (cache.has(root.dataset.receptorId)) update(root, cache.get(root.dataset.receptorId)); }); }
  function scan() { const roots = [...document.querySelectorAll(".rating-widget")]; roots.forEach(root => { if (!root.dataset.bound) { root.dataset.bound = "1"; if (!cache.has(root.dataset.receptorId)) cache.set(root.dataset.receptorId, { total: 0, up: 0, down: 0, positive_pct: 0 }); update(root, cache.get(root.dataset.receptorId)); } }); load(roots.map(root => root.dataset.receptorId)); }
  function init() { scan(); const list = document.getElementById("list"); if (list) new MutationObserver(scan).observe(list, { childList: true }); }
  window.ReceptoresRatings = { widget, scan };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init); else init();
})();
