(() => {
  "use strict";
  const API = "https://receptores-analytics.adminbase100.workers.dev";
  const REASONS = ["rapidez", "comunicacion", "disponibilidad", "cumplimiento", "trato", "honorarios"];
  const LABELS = { rapidez: "Rapidez", comunicacion: "Comunicación", disponibilidad: "Disponibilidad", cumplimiento: "Cumplimiento", trato: "Trato", honorarios: "Honorarios" };
  const DEBUG = new URLSearchParams(location.search).get("debug") === "ratings";
  const cache = new Map();
  const turnstileStates = new WeakMap();
  const log = (...args) => DEBUG && console.log("[ratings]", ...args);
  function browserId() {
    try { let id = localStorage.getItem("receptores_browser_id"); if (!/^[A-Za-z0-9_-]{16,128}$/.test(id || "")) { id = crypto.randomUUID().replaceAll("-", ""); localStorage.setItem("receptores_browser_id", id); } return id; } catch { return ""; }
  }
  function myVote(id) { try { return Number(localStorage.getItem(`receptores_vote:${id}`)) || 0; } catch { return 0; } }
  function setMyVote(id, vote) { try { localStorage.setItem(`receptores_vote:${id}`, String(vote)); } catch {} }
  function debugError(error) { log("error", error); }
  function widget(id) {
    const root = document.createElement("section"); root.className = "rating-widget"; root.dataset.receptorId = id; root.setAttribute("aria-label", "Recomendación y comentario privado");
    root.innerHTML = `<div class="rating-title">Recomendaciones</div><div class="rating-summary" aria-live="polite">Cargando recomendaciones…</div><div class="rating-actions"><button type="button" data-recommend aria-label="Recomendar receptor" aria-pressed="false">Recomendar</button><button type="button" data-feedback-toggle>Enviar comentario privado</button></div><p class="rating-note">Las recomendaciones son anónimas. Los comentarios son privados.</p><form class="rating-feedback" hidden><fieldset><legend>¿Qué influyó en tu experiencia?</legend>${REASONS.map(reason => `<label><input type="checkbox" name="reason" value="${reason}"> ${LABELS[reason]}</label>`).join("")}</fieldset><label class="rating-comment">Comentario opcional<textarea name="comment" maxlength="300" rows="3"></textarea></label><div class="turnstile-slot"></div><button type="submit">Enviar comentario</button><span class="rating-message" role="status"></span></form>`;
    root.addEventListener("click", event => { if (event.target.closest("button[data-recommend]")) chooseRecommend(root); if (event.target.closest("button[data-feedback-toggle]")) toggleFeedback(root); });
    root.querySelector("form").addEventListener("submit", event => { event.preventDefault(); requestSubmission(root, submitFeedback); });
    return root;
  }
  function update(root, rating) { const total = rating.recommendations || 0; root.querySelector(".rating-summary").textContent = `${total} ${total === 1 ? "recomendación" : "recomendaciones"}`; const button = root.querySelector("button[data-recommend]"); const active = isRecommended(root.dataset.receptorId); button.classList.toggle("is-selected", active); button.setAttribute("aria-pressed", String(active)); button.textContent = active ? "Recomendado" : "Recomendar"; }
  function turnstileState(root) { let state = turnstileStates.get(root); if (!state) { state = { widgetId: null, pending: false, pendingSubmit: null, submitting: false }; turnstileStates.set(root, state); } return state; }
  function isRecommended(id) { try { return localStorage.getItem(`receptores_recommendation:${id}`) === "1" || myVote(id) === 1; } catch { return myVote(id) === 1; } }
  function markRecommended(id) { try { localStorage.setItem(`receptores_recommendation:${id}`, "1"); } catch {} }
  function chooseRecommend(root) { const state = turnstileState(root); if (state.submitting || isRecommended(root.dataset.receptorId)) return; requestSubmission(root, submitRecommendation); }
  function toggleFeedback(root) { const form = root.querySelector(".rating-feedback"); form.hidden = !form.hidden; if (!form.hidden) root.querySelector(".rating-message").textContent = ""; }
  function ensureTurnstile(root) { const key = window.RECEPTORES_TURNSTILE_SITE_KEY || ""; const slot = root.querySelector(".turnstile-slot"); const state = turnstileState(root); if (!key) { slot.textContent = "Configura Turnstile para enviar."; return; } if (state.widgetId !== null || slot.dataset.widgetId) { state.widgetId = state.widgetId === null ? slot.dataset.widgetId : state.widgetId; return; } if (!window.turnstile) { slot.textContent = "No fue posible cargar la verificación de seguridad."; return; } const widgetId = window.turnstile.render(slot, { sitekey: key, callback: token => { slot.dataset.token = token; if (state.pending && !state.submitting) { const submit = state.pendingSubmit; state.pending = false; state.pendingSubmit = null; if (submit) submit(root); } }, "expired-callback": () => { delete slot.dataset.token; if (state.pending) root.querySelector(".rating-message").textContent = "La verificación expiró. Inténtalo nuevamente."; }, "error-callback": () => { delete slot.dataset.token; state.pending = false; state.pendingSubmit = null; root.querySelector(".rating-message").textContent = "No fue posible validar la verificación de seguridad."; } }); state.widgetId = widgetId; slot.dataset.ready = "1"; slot.dataset.widgetId = String(widgetId); }
  function requestSubmission(root, submit) { const state = turnstileState(root); const slot = root.querySelector(".turnstile-slot"); const hadWidget = state.widgetId !== null || Boolean(slot.dataset.widgetId); state.pending = true; state.pendingSubmit = submit; ensureTurnstile(root); if (hadWidget) { delete slot.dataset.token; window.turnstile.reset(state.widgetId); } }
  async function submitRecommendation(root) { const state = turnstileState(root); if (state.submitting) return; const slot = root.querySelector(".turnstile-slot"), id = root.dataset.receptorId, token = slot.dataset.token || "", message = root.querySelector(".rating-message"); if (!token) { message.textContent = "Completa la verificación de seguridad para recomendar."; return; } state.submitting = true; delete slot.dataset.token; const payload = { receptor_id: id, vote: 1, browser_id: browserId(), turnstile_token: token }; log("recommendation sent", { ...payload, turnstile_token: "[redacted]" }); try { const response = await fetch(`${API}/vote`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); log("recommendation response", data); if (!response.ok) { const error = new Error(data.error || `HTTP ${response.status}`); error.code = data.error; throw error; } markRecommended(id); cache.set(id, data); update(root, data); message.textContent = "Recomendación guardada."; } catch (error) { message.textContent = error.code === "daily_recommendation_limit" ? "Ya usaste tus 5 recomendaciones de hoy. Vuelve mañana =)" : "No fue posible guardar la recomendación."; debugError(error); } finally { delete slot.dataset.token; state.submitting = false; state.pending = false; state.pendingSubmit = null; } }
  async function submitFeedback(root) { const state = turnstileState(root); if (state.submitting) return; const form = root.querySelector("form"), slot = root.querySelector(".turnstile-slot"), id = root.dataset.receptorId, token = slot.dataset.token || "", reasons = [...form.querySelectorAll("input[name=reason]:checked")].map(input => input.value), comment = form.comment.value.trim(), message = root.querySelector(".rating-message"); if (!token) { message.textContent = "Completa la verificación de seguridad para enviar."; return; } state.submitting = true; delete slot.dataset.token; const payload = { receptor_id: id, browser_id: browserId(), turnstile_token: token, reasons, comment }; log("private feedback sent", { ...payload, turnstile_token: "[redacted]" }); try { const response = await fetch(`${API}/feedback`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); log("private feedback response", data); if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`); message.textContent = "Comentario privado enviado."; form.reset(); } catch (error) { message.textContent = "No fue posible enviar el comentario privado."; debugError(error); } finally { delete slot.dataset.token; state.submitting = false; state.pending = false; state.pendingSubmit = null; } }
  async function load(ids) { const missing = [...new Set(ids)].filter(id => !cache.has(id)); if (!missing.length) return; log("batch requested", missing); try { const response = await fetch(`${API}/ratings?ids=${encodeURIComponent(missing.join(","))}`); const data = await response.json(); if (!response.ok) throw new Error(data.error || `HTTP ${response.status}`); log("batch received", data); Object.entries(data.ratings || {}).forEach(([id, rating]) => cache.set(id, rating)); } catch (error) { debugError(error); } document.querySelectorAll(".rating-widget").forEach(root => { if (cache.has(root.dataset.receptorId)) update(root, cache.get(root.dataset.receptorId)); }); }
  function scan() { const roots = [...document.querySelectorAll(".rating-widget")]; roots.forEach(root => { if (!root.dataset.bound) { root.dataset.bound = "1"; if (cache.has(root.dataset.receptorId)) update(root, cache.get(root.dataset.receptorId)); else root.querySelector(".rating-summary").textContent = "Cargando recomendaciones…"; } }); load(roots.map(root => root.dataset.receptorId)); }
  function init() { scan(); const list = document.getElementById("list"); if (list) new MutationObserver(scan).observe(list, { childList: true }); }
  window.ReceptoresRatings = { widget, scan };
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init); else init();
})();
